title:              PhoenixCTF
email:              hello+PhoenixCTF@transtechtent.com
description:        Rebuilding the National Trans Memorial
author:             Trans Tech Tent
baseurl:            ""
url:                "https://phoenixctf.github.io"

# Social Profiles
twitter_username:   TransCTF
github_username:    Trans-Tech-Tent
facebook_username:  TransTechTent
instagram_username:  TransTechTent
linkedin_username:  trans-tech-tent

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
